ALE Namespace wrapper for emucore
mgbellemare/Arcade-Learning-Environment pull request #445
Opened 2022-01-09 21:57 UTC by tuero

The emucore code has naked class definitions such as `Device`, which makes it difficult to link with other libraries. One example of this is libtorch C++. This pull request wraps the code in emucore inside the ale namespace. The resulting effect is that this change allows to link against libtorch (which also defined a `Device`) without any linking errors.

2022-01-10 19:40 UTC, JesseFarebro requested changes
Hi @tuero,

Thanks for the contribution! This has been on my to-do list for quite some time. The only thing I'd like to see changed is that everything in `emucore/` is namespaced as `ale::stella`. Other than that it looks good.

2022-01-11 23:36 UTC, tuero commented
@JesseFarebro Thanks for the suggestion! I've updated emucore to be under the `ale::stella` namespace. As a result, all references to any classes in emucore also need to reference the `stella` namespace (everything is already under `ale` but not `stella`). 

Unfortunately, although these changes are minor, a lot of files are touched as a result. I've broken it up into several commits grouped so that the pull request review is easier to follow. Since all commits are needed without breaking anything, I would suggest squashing them before this pull request gets merged

2022-01-18 01:32 UTC, JesseFarebro commented
@tuero sorry for the delay, I will be getting around to this. Thanks for making these changes, I just need to dedicate some time to look everything over before the next release. This will coincide with the release of Gym 0.22.

2022-02-16 02:29 UTC, merged

2022-02-16 02:29 UTC, JesseFarebro commented
Thanks for the contribution @tuero!